language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
script:
    - python manage.py test --settings=projetoextensao.settings.prod
branches:
    only:
        - master
deploy:
    provider: heroku
    api_key:
        secure: $HEROKU_KEY
